bitpanda-labs/loggo2

loggo/loggo.py

override fields if we want to

---

.bumpversion.cfg
README.md
loggo/__init__.py
loggo/loggo.py
setup.py
tests/tests.py

Readme limitation

---

loggo/loggo.py

max dict depth for obscure dict values or remove dict keys

23 recursively obscure private keys

---

.travis.yml
tests/tests.py

25 travis ci

---

README.md
loggo/loggo.py

Add events

---

loggo/loggo.py
tests/tests.py

Make max_dict_depth configurable, improve, the censoring method, and add more tests to make sure that it works recursively, but also respected max_dict_depth

confirm that recursive private data removal works

---

.travis.yml
CHANGELOG.md
loggo/loggo.py
requirements.txt
setup.py
tests/tests.py

Half of the codebase typehinted. Increased python minimum requirement to 3.6, thus a major version bump should be made after merging.

Add typehints

---

.bumpversion.cfg
README.md
loggo/__init__.py
setup.py

* Gives us a version with PEP561 compatibility.

Bump version: 5.0.0 → 5.1.0

---

CHANGELOG.md
README.md
loggo/loggo.py
tests/test_basics.py
tests/test_custom_strings.py
tests/test_method_types.py

I also split up the massive test file

WIP: remove Loggo.events and change config to kwargs

---

CHANGELOG.md
loggo/loggo.py

* Remove Loggo.verbose contextmanager
* Disallow None as value for keyword argument `obscured` when initializing.

Remove verbose

---

README.md

Ran black on individual python sections for obvious reasons.

used black on all individual python stubs

---

.pre-commit-config.yaml
README.md
tests/test_basics.py
tests/test_custom_strings.py

* More comprehensive pre-commit hooks and mentioning them in the README.
* Style guide in the README

Pre commit hooks and style guide

---

.pre-commit-config.yaml
loggo/loggo.py
mypy.ini
tests/test_basics.py

1. Run `pre-commit autoupdate`.
2. Add new mypy config `warn_unreachable`.
3. Fix the warnings for unreachable code

Add new mypy config `warn_unreachable`.

---

loggo/loggo.py

Closes https://github.com/bitpanda-labs/loggo/issues/86

Fix loggo throwing an error if inspect.signature fails

---

.pre-commit-config.yaml
.travis.yml
CHANGELOG.md
loggo/__init__.py
loggo/loggo.py
requirements.txt
setup.py
tests/test_basics.py
tests/test_method_types.py

- Docformatter for docstrings
- Make write_to_file() and logme() private methods

Docformatter for docstrings

---

loggo/_loggo.py

- Dont mutate the log data passed by users
- Change Dict typings to immutable Mappings

Dont mutate user input

---

loggo/_loggo.py
tests/test_basics.py

- Truncate to `max_len` instead of `max_len + 3`
- Add docs for truncate parameters

Fix truncation length. Add docs for truncation stuff

---

.pre-commit-config.yaml
CHANGELOG.md
loggo/_loggo.py

- Dont allow None value for private_data
- Allow frozensets

Dont allow None for private_data

---

.coveragerc
tests/test_basics.py

Speed up the two tests that take the most time. From around 2s and 3s to near 0s.

Test speedup

---

setup.py

See https://github.com/python/mypy/issues/8802#issuecomment-628249236 )

Remove zip_safe=False

---

.bumpversion.cfg
CHANGELOG.md
README.md
loggo2/__init__.py
loggo2/_loggo2.py
setup.py
tests/test_basics.py
tests/test_custom_strings.py

Log level of INFO is a more appropriate default and the desired log level for most consumers of this library.

Set default log level to INFO
